# Generated by Django 3.2.12 on 2022-11-29 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='question',
            field=models.TextField(default='No text just connecting'),
        ),
    ]
