# Generated by Django 3.2.12 on 2022-12-08 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgapp', '0006_cartext'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=250)),
                ('mission', models.CharField(max_length=100)),
                ('plan', models.CharField(max_length=100)),
                ('vision', models.CharField(max_length=100)),
            ],
        ),
    ]
