# Generated by Django 3.2.12 on 2022-12-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgapp', '0007_aboutus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='static/')),
                ('name', models.CharField(max_length=50)),
                ('desg', models.CharField(max_length=50)),
                ('twitter', models.URLField(max_length=50)),
                ('linkedin', models.URLField(max_length=50)),
                ('gmail', models.URLField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='mission',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='plan',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='text',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='vision',
            field=models.TextField(max_length=250),
        ),
    ]
