# Generated by Django 3.2.12 on 2022-12-08 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgapp', '0011_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icontext', models.CharField(max_length=50)),
                ('heading', models.CharField(max_length=50)),
                ('text', models.TextField(max_length=1000)),
                ('link', models.URLField(max_length=50)),
            ],
        ),
    ]
