# Generated by Django 3.2.12 on 2022-12-08 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgapp', '0013_auto_20221208_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('heading', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('desc', models.TextField()),
                ('link', models.URLField()),
            ],
        ),
    ]
