# Generated by Django 3.2.12 on 2022-12-08 19:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tgapp', '0014_blogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='static/'),
            preserve_default=False,
        ),
    ]
