# Generated by Django 3.2.12 on 2022-12-08 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgapp', '0015_blogs_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.CharField(max_length=5)),
                ('heading', models.CharField(max_length=50)),
                ('jobdesc', models.CharField(max_length=100)),
                ('reqskill', models.CharField(max_length=100)),
                ('apply', models.BooleanField(default=True)),
            ],
        ),
    ]
