# Generated by Django 3.2.12 on 2022-12-12 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgapp', '0017_working'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Apply',
            new_name='CourseApplied',
        ),
    ]
