# Generated by Django 3.2.12 on 2022-12-12 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgapp', '0018_rename_apply_courseapplied'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='GetInTouch',
        ),
    ]
