# Generated by Django 3.2.12 on 2022-12-12 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgapp', '0019_rename_contact_getintouch'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Career',
            new_name='Jobs',
        ),
    ]
