# Generated by Django 3.2.12 on 2022-12-12 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgapp', '0020_rename_career_jobs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cartext',
            new_name='Carousal',
        ),
    ]
