# Generated by Django 3.2.12 on 2022-12-12 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgapp', '0021_rename_cartext_carousal'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blogs',
            new_name='Blog',
        ),
        migrations.RenameModel(
            old_name='Jobs',
            new_name='Job',
        ),
        migrations.RenameModel(
            old_name='LinkServices',
            new_name='LinkService',
        ),
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
    ]
