# Generated by Django 3.2.12 on 2023-01-11 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgapp', '0028_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/')),
                ('heading', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=50)),
                ('start', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='static/')),
                ('price', models.CharField(max_length=10)),
                ('apply', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Courses',
        ),
    ]
