# Generated by Django 3.2.12 on 2023-01-11 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgapp', '0029_auto_20230111_0913'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientandCollab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/')),
                ('alt', models.CharField(max_length=50)),
            ],
        ),
    ]
