# Generated by Django 3.2.12 on 2023-01-11 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgapp', '0030_clientandcollab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='start',
            field=models.DateField(),
        ),
    ]
