# Generated by Django 3.2.12 on 2023-01-11 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgapp', '0031_alter_course_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='start',
            field=models.CharField(max_length=50),
        ),
    ]
