# Generated by Django 3.2.12 on 2023-01-11 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgapp', '0033_alter_course_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='course',
            name='price',
        ),
    ]
