# Generated by Django 3.2.12 on 2023-01-13 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgapp', '0034_auto_20230111_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='start',
        ),
    ]
